### ISSUE TITLE
Keep the comments

### ISSUE THREAD

**Issue by kissu** [plaidev/pug-to-html#2]
Hi, it's working great. :confetti_ball: 
Meanwhile, I was wondering if it was possible to keep the unbuffered comments while converting it to `html`.

Indeed, the following is converted to nothing :thinking: 
```pug
//- unbuffered comment
```

While it does perfectly keep those
```pug
// Regular comment
```
when in html
```html
<!--Regular comment-->
```

**Comment by kazupon** [comment]
Thank you for your feedback!

hmm, 🤔 
It's specification of pug that `//-` cannot be converted as HTML comment.

You can avoid this problem by converting the pug comment of vue components like the following shell script.

```sh
$ find ./src/components -name "*.vue" -not -path "*/node_modules/*" | xargs sed -i -e "s/\/\/\-/\/\//"
```

**Comment by kissu** [comment]
Thanks, indeed just realized that "hidden" comments cannot be done in regular HTML (without Webpack removing them for the production). :ok_hand:
